# Generated by Django 5.1 on 2024-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_propietario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
